### ISSUE TITLE
Remove lattice.einsum in favor of torch.einsum

### ISSUE THREAD

**Issue by MartinKliemank** [lettucecfd/lettuce#111]
As far as I understand it, lattice.einsum is basically a wrapper that allows to omit the "..." in the dimension-equation (feel free to correct me if it has a greater purpose than that).
- In my opinion leaving out the "..." makes the code less readable, since it doesn't show that there are more dimensions than listed. 
- Lattice.einsum also doesn't work if you only want to use it on parts of the domain, which makes it unusable in boundary conditions and the likes.

So I think it would be better to phase out lattice.einsum and return to the bare torch.einsum.

**Comment by rawbby** [comment]
Furthermore, I experienced difficulties in understanding the differences between "lattice.einsum" and "torch.einsum". I think "lattice.einsum" makes the code harder to understand for newcomers.

**Comment by Olllom** [comment]
Historically, this was added to the `Lattice` to experiment with different memory layouts (array-of-structure vs. structure-of-array; see #6 and #8). Since we've settled fully on the SoA layout, I agree that it can be removed.

Feel free to open a PR.

**Comment by PhiSpel** [comment]
I agree that we should return to torch.einsum, which is also much better documented and supported online.

@McBs solving #175 should also solve this issue.

**Comment by MartinKliemank** [comment]
Woo, my issue was resolved, finally! :D
