### ISSUE TITLE
Obstacle2D/ 3D Grid

### ISSUE THREAD

**Issue by robert-DL** [lettucecfd/lettuce#115]
Hi, 

I am quite unsure about the implementation of the obstacle class in 2d and 3d. The grid is initialized with stop_x and stop_y by dividing the resolution with the characteristic length which is given in lattice units. However, this changes the geometry I am using when I increase the resolution. It may be, that I got something wrong since I am from a FEM background, but this seems odd to me. I would be happy about an explanation. Shall I subclass the obstacle class if I want to change that (e.g. for using a fixed geometry)?

```
def grid(self):
    stop_x = self.resolution_x / self.units.characteristic_length_lu
    stop_y = self.resolution_y / self.units.characteristic_length_lu

    x = np.linspace(0, stop_x, num=self.resolution_x, endpoint=False)
    y = np.linspace(0, stop_y, num=self.resolution_y, endpoint=False)

    return np.meshgrid(x, y, indexing='ij')
```

Best. 
Robert

**Comment by Olllom** [comment]
Hi Robert,

The `Obstacle` classes are currently implemented in a characteristic unit system. That means that the "physical units" are actually characteristic units in the unit system given by the obstacle length `L` and the inflow velocity `u`. 

We usually create the masks from the grid. For example:

```
lattice = lt.Lattice(lt.D2Q9, "cpu")
flow = lt.Obstacle2D(
    100, 50,
    reynolds_number=1.0,
    mach_number=0.1,
    lattice=lattice,
    char_length_lu=10
)
x, y = flow.grid
flow.mask = ((x >= 2) & (x < 3) & (y >= 2) & (y < 3))
```
would give you a square of length 1. Whenever you change the resolution, you also have to change `char_length_lu` accordingly but the code for the mask stays the same.

To be honest, I am not super happy with this implementation myself. I would prefer to have a second constructor that takes only physical units. Something like this.

```
 @staticmethod
 def from_physical_units(
    resolution_x, resolution_y,
    reynolds_number, mach_number, 
    lattice, domain_length_x, 
    char_length, char_velocity=1
):
    ...
```

**Comment by Olllom** [comment]
Does this answer your question?

**Comment by robert-DL** [comment]
This is also what I did right now, but it seems cumbersome since you normally have a fixed geometry and the Reynolds number. The proposed method would be quite useful. Not sure if I can implement this, my experience level in LBM is more beginner currently, but maybe it will arise naturally in my work.  But yes, it answers my question.

**Comment by Olllom** [comment]
I just suggested a change to the obstacle code as described above, see #116. I would like to wait if @MartinKliemank has comments before I merge it -- he's the original author of the `Obstacle` code. So long, feel free to work on the `obstacle` branch of the repo.

**Comment by Olllom** [comment]
see https://github.com/lettucecfd/lettuce/blob/obstacle/examples/obstacle.ipynb

**Comment by robert-DL** [comment]
Thanks for the fast fix! I will check the new implementation.

In my case, I decided to add geometries via a wrapper. I am just specifying the shape of the obstacle in a YAML-file, together with its origin. A dictionary is passed to a function that automatically fills in the obstacle. While not necessary, I think this could make things easier for people that want to use lettuce more "UI - like". Instead of writing code, one just needs to create the dictionary data and make a call to the class/ method. But just an idea.

**Comment by Olllom** [comment]
Sounds interesting. I agree that in the long run a UI-like flow definition would be nice.
How would such a yaml file look like in your case?

**Comment by robert-DL** [comment]
At the moment, very likely like this (although not perfect)
´´´
sampling:
  n_steps: 20000
  start_saving: 20000
  mach_numbers: [0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
  reynolds_numbers: [25, 50, 75, 100, 125]

lbm_config:
  flow: "Obstacle2D"
  stencil: "D2Q9"
  streaming: "StandardStreaming"
  flow_config:
    flow_params:
      shape: [401, 201]
      reynolds_number: 50
      mach_number: 0.05
      domain_length_x: 15.0
    obstacles:
      1:
        name: "cylinder"
        shape: "circle"   # Circle vs rectangular
        P0: [4.5, 4.5]   # [x0, y0]
        radius: 1.
  collision: "BGKCollision"
  observables: ["Velocity", "Distribution"]
´´´

**Comment by Olllom** [comment]
OK, looks cool.
There are certainly upsides to this kind of frontend.
Personally, I prefer to work directly with the Python API.

I'll mark this issue as resolved for now, but feel free to open a new one for follow-ups. And just note that #116 will deprecate the old Obstacle API once it's merged.
