### ISSUE TITLE
Subprocess.CalledProcessError:Comman'['PATH'','setup.py,install]'returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Puffmakki** [lettucecfd/lettuce#129]
Hi
When I ran "python setup.py test" on Ubuntu. The prcoess was interuptted by this error 
[subprocess.CalledProcessError: Command '['.\CONDA\\envs\\lettuce\\python.exe', 'setup.py', 'install']' returned non-zero exit status 1.]
How can I deal with it?
Thank you for your help.

**Comment by Olllom** [comment]
Hard to say without knowing which of the tests fail. Can you give a more detailed error message? Maybe also check the output of running `pytest -vs`
