### ISSUE TITLE
Add a new fluid source in obstacle.ipynb

### ISSUE THREAD

**Issue by YaxinCui** [lettucecfd/lettuce#137]
[examples](https://github.com/lettucecfd/lettuce/tree/master/examples)
in obstacle.ipynb, How to add a fluid source of air pollen particles to add new fluids to the space?

**Comment by Olllom** [comment]
This feature is currently not supported.

**Comment by YaxinCui** [comment]
I think it is possible to modify the fluid density of the grid in Lettuce after the stream to simulate fluid source.
Which class or function i need to modify?

**Comment by Olllom** [comment]
Would pollen particles not be modeled as passive scalars? Why would you want to model them as a density source?On Apr 26, 2023, at 08:47, Yaxin ***@***.***> wrote:﻿
I think it is possible to modify the fluid density of the grid in Lettuce after the stream to simulate fluid source.
Which class or function i need to modify?

**Comment by YaxinCui** [comment]
Because I want to simulate the spread of pollen on trees.
We assume that a tree can produce pollen for a sustained period of time.

**Comment by YaxinCui** [comment]
如何在障碍物中模拟被动标量？doc中有一个例子吗？

**Comment by YaxinCui** [comment]
How to simulate passive scalars in obstacles? Is there an example in the doc?

**Comment by Olllom** [comment]
You can model mass sources by a custom collision operator. See for instance https://pubs.aip.org/aip/pof/article/30/5/057104/911792/On-the-inclusion-of-mass-source-terms-in-a-single

The collision routine from that paper is currently not implemented in lettuce but feel free to open a PR if you want to contribute it as a new feature.

**Comment by YaxinCui** [comment]
> 
Oh, thank you. The diffusion of pollen is indeed not a fluid.
I previously hoped to use LBM to simulate the process of pollen wall collision.

Can you recommend an other software to simulate the process of gas diffusion, while also considering the collision situation of pollen when encountering obstacles?
