### ISSUE TITLE
Error with installation 

### ISSUE THREAD

**Issue by okhsallam** [lettucecfd/lettuce#138]
Dear, 
I followed the installation steps on my Linux workstation.

When I run the command **python setup.py install**

This error showed up:
 setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'master'

Thanks in advance

**Comment by McBs** [comment]
Hello,

We've recently updated our system requirements to address this issue. To ensure compatibility, please make sure that your environment matches the updated requirements, specifically the CUDA version compatible with the latest version of PyTorch we are now using. Please feel free to reach out if you encounter any further issues or have any more questions.
