### ISSUE TITLE
Question about porous_medium

### ISSUE THREAD

**Issue by Neo-Zhu** [lettucecfd/lettuce#140]
Hi, i am a new lettuce users. When i run the example of porous_medium, there is an error:

     class PorousMedium2D(lt.Obstacle2D):
TypeError: function() argument 1 must be code, not str

I check the code, and notice that the lt.Obstacle2D is a function defined in obstacle.py:

def Obstacle2D(resolution_x, resolution_y, reynolds_number, mach_number, lattice, char_length_lu):
    warnings.warn("Obstacle2D is deprecated. Use Obstacle instead", DeprecationWarning)
    shape = (resolution_x, resolution_y)
    domain_length_x = resolution_x / char_length_lu
    return Obstacle(shape, reynolds_number, mach_number, lattice, domain_length_x=domain_length_x)

Therefore, in my python, class PorousMedium2D can not inherit from the  lt.Obstacle2D as the type of lt.Obstacle2D is not a class. 

I wanna know what i can do to solve the problem.

Thanks in advanced for your answer!

**Comment by McBs** [comment]
We have updated the examples to ensure they work appropriately now. Please try running the updated examples and let us know if you encounter any issues.
