### ISSUE TITLE
Where are the Neural Network Features?

### ISSUE THREAD

**Issue by foss98** [lettucecfd/lettuce#141]
I can't seem to find reference to any neural network model being used as the relaxation parameters (unless the output was hardcoded, but even then, it seems generalised for different flow types as the stencils are interchangeable). An indication in the code of where this happens would be good. Additionally, I also can't seem to find GPU acceleration through torch.autograd, was this feature cut?

**Comment by McBs** [comment]
The related information you're looking for can be found in our documentation at [lettuce-paper on GitHub](https://github.com/lettucecfd/lettuce-paper). Please visit this link to access detailed explanations and additional resources.
