### ISSUE TITLE
class that inherit Obstacle2D cannot be compiled 

### ISSUE THREAD

**Issue by mingmingbuxiao** [lettucecfd/lettuce#145]
`import lettuce as lt

class PorousMedium2D(lt.Obstacle2D):
    ...
`
lt.Obstacle2D is recognized by Python as a function， PorousMedium2D class cannot be compiled.The error prompt is ‘TypeError: function() argument 'code' must be code, not str‘.
what can I do ?

**Comment by mingmingbuxiao** [comment]
![2023-10-25 22-50-44屏幕截图](https://github.com/lettucecfd/lettuce/assets/42938413/6f1acd6a-a6d1-42cf-94e0-a0ef297e664b)
I find some info，let me try

**Comment by McBs** [comment]
We have updated the examples to ensure they work appropriately now. Please try running the updated examples and let us know if you encounter any issues.
