### ISSUE TITLE
something wrong when run the test cases

### ISSUE THREAD

**Issue by mingmingbuxiao** [lettucecfd/lettuce#146]
![2023-10-26 18-52-09屏幕截图](https://github.com/lettucecfd/lettuce/assets/42938413/33168414-38ce-428a-a5d4-5a27dfe44f9b)

**Comment by McBs** [comment]
Thank you for bringing this to our attention. We have already noticed the issue and have been able to narrow it down. It relates to specific combinations of the native extension. As a workaround, using <lattice=Lattice(..., use-native=False)> should resolve the issue in the meantime.
