### ISSUE TITLE
STL processing to mesh

### ISSUE THREAD

**Issue by MitchChild** [lettucecfd/lettuce#152]
Hey there, I was curious if there was documentation/recommendations on best practice for preparing an stl to work in lettuce for LBM aerodynamic testing. I'm curious if there's any recommended tools for creating a mesh from an stl and if there is any guidance on a workflow in lettuce.

thanks!

**Comment by McBs** [comment]
Hi Mitch,

Apologies for the delayed response. At the moment, meshes need to be manually generated within the Flow class. However, we are actively planning to develop an API that will support importing .stl files. This will streamline the process and enhance functionality.
