### ISSUE TITLE
How to run a two phase flow

### ISSUE THREAD

**Issue by scottzyy** [lettucecfd/lettuce#153]
I tested the porous_medium.ipynb and it was pretty fast on the GPU. Can it be used to simulate a two-phase flow? How to set the parameters? Thank you!

**Comment by McBs** [comment]
Hi scottzyy,

currently, multi-phase flows are not supported by default in Lettuce. To use multi-phase flows, you will need to modify the simulation.py file. This involves adding an additional distribution function and applying the established methods to it.

Bests
Mario
