### ISSUE TITLE
[Feature]: change readme install instructions

### ISSUE THREAD

**Issue by McBs** [lettucecfd/lettuce#234]
Ideally, we want users to be able to install directly from `requirements.txt` - if they are using a compatible GPU

**Comment by PhiSpel** [comment]
Issues:

- [ ] `pytorch` conda package 2.4 is not yet available for mac
- [ ] I was unable to install `pytorch=2.4`
- [ ] `pytorch-cuda` is not yet in `requirements.txt` - should it be?

Learnings:

- [ ] `conda list -e > requirements.txt -c pytorch -c nvidia -c conda-forge` to install requirements
