### ISSUE TITLE
Unnecessary assertions in BounceBackBoundary.__init__

### ISSUE THREAD

**Issue by rawbby** [lettucecfd/lettuce#81]
In file lettuce/boundary.py:BounceBackBoundary.\_\_init\_\_

"I actually don't think these lines will ever throw a LettuceException. Rather, they will raise AssertionError which does not seem to be the desired behavior."
_Originally posted by @Olllom in https://github.com/lettucecfd/lettuce/pull/80#r644350399_

**Comment by rawbby** [comment]
I think instead of the assertions a documentation of the parameters would be good.

**Comment by PhiSpel** [comment]
@rawbby your PR solves this, right?
